#!/usr/bin/env bash

set -x

BASENAME=`basename -s .ez $1`
WORK_DIR=`mktemp -d "/tmp/${BASENAME}_XXXXXX"`
echo Working Directory: $WORK_DIR

./_build/default/bin/ezfront.exe $1 $WORK_DIR/$BASENAME.irpb
./_build_back/ezback $WORK_DIR/$BASENAME.irpb $WORK_DIR/$BASENAME.o
clang++ -pie -o $WORK_DIR/$BASENAME $WORK_DIR/$BASENAME.o -L./_build_std -lezstd -Wl,-rpath=.
cp ./_build_std/libezstd.so $WORK_DIR
